# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('item_id', models.IntegerField()),
                ('description', models.TextField(default=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('sale_price', models.DecimalField(decimal_places=3, default=9.99, max_digits=8)),
            ],
        ),
    ]
